apiVersion: batch/v1
kind: Job
metadata:
  name: sirius-rs-lift3
spec:
  template:
    spec:
      # This part asks for preferred GPU (no guarantee)
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values: # Set the GPU type
                - NVIDIA-GeForce-GTX-1080-Ti
      # This part asks for preferred GPU (no guarantee)
      containers:
      - name: gpu-container
        image: nvidia/cudagl:11.3.0-devel-ubuntu20.04 # Choose desired docker image
        command: ["sleep", "infinity"]
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: 300Gi
            cpu: "16"
            # memory: 32Gi
          requests:
            memory: 200Gi
            cpu: "8"
            # memory: 16Gi
            nvidia.com/gpu: 1
        # This part mounts our lab's PVC
        volumeMounts:
        - mountPath: /home/saqibcephsharedvol2
          name: saqibcephsharedvol2
        - mountPath: /home/erl-ucsd
          name: erl-ucsd
        - mountPath: /dev/shm
          name: shm
      restartPolicy: Never
      volumes:
        - name: saqibcephsharedvol2
          persistentVolumeClaim:
            claimName: saqibcephsharedvol2
        - name: erl-ucsd
          persistentVolumeClaim:
            claimName: erl-ucsd
        - name: shm
          emptyDir:
            medium: Memory
      # This part mounts our lab's PVC