apiVersion: batch/v1
kind: Job
metadata:
  name: sirius-job1
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:    # ask for a specific GPU type (no guarantee)
                - NVIDIA-GeForce-GTX-1080-Ti
                - NVIDIA-GeForce-RTX-2080-Ti
                - NVIDIA-TITAN-RTX
                - NVIDIA-GeForce-RTX-3090
                - NVIDIA-A100-80GB-PCIe-MIG-1g.10gb
                - NVIDIA-A10
      containers:
      - name: gpu-container
        image: nvidia/cudagl:11.3.0-devel-ubuntu20.04    # Choose desired docker image
        command:            # NEVER EVER USE "sleep infinity" command FOR JOBS
        - "python"     
        args:
        - "/opt/repo/REPONAME/my_script.py"
        - "arg_job_to_run"
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: 100Gi
            cpu: "16"
          requests:
            nvidia.com/gpu: 1
            memory: 50Gi    # use half of memory in limits
            cpu: "8"
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        - name: saqibcephsharedvol2
          mountPath: /home/saqibcephsharedvol2
        - name: erl-ucsd
          mountPath: /home/erl-ucsd
        - name: shm
          mountPath: /dev/shm 
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          # - https://gitlab.nrp-nautilus.io/USERNAME/REPONAME
          - /opt/repo/REPONAME
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
      volumes:
        - name: saqibcephsharedvol2
          persistentVolumeClaim:
            claimName: saqibcephsharedvol2
        - name: erl-ucsd
          persistentVolumeClaim:
            claimName: erl-ucsd
        - name: shm
          emptyDir:
            medium: Memory
      restartPolicy: Never